### ISSUE TITLE
Timeout to start server

### ISSUE THREAD

**Issue by unkcpz** [aiidateam/aiida-hyperqueue#15]
Got following error when start the hq server in EIGER. The server is started successfully although. Trace back `aiida-core` and open issue https://github.com/aiidateam/aiida-core/issues/6377

```
Traceback (most recent call last):
  File "/home/jyu/.aiida_venvs/sssp-project/bin/verdi", line 8, in <module>
    sys.exit(verdi())
  File "/home/jyu/.aiida_venvs/sssp-project/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/jyu/.aiida_venvs/sssp-project/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/jyu/.aiida_venvs/sssp-project/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jyu/.aiida_venvs/sssp-project/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jyu/.aiida_venvs/sssp-project/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  [Previous line repeated 1 more time]
  File "/home/jyu/.aiida_venvs/sssp-project/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jyu/.aiida_venvs/sssp-project/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/jyu/project/sssp-project/aiida-core/src/aiida/cmdline/utils/decorators.py", line 102, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/jyu/project/sssp-project/aiida-hyperqueue/aiida_hyperqueue/cli.py", line 34, in start_cmd
    retval, _, stderr = transport.exec_command_wait(
  File "/home/jyu/project/sssp-project/aiida-core/src/aiida/transports/transport.py", line 413, in exec_command_wait
    retval, stdout_bytes, stderr_bytes = self.exec_command_wait_bytes(command=command, stdin=stdin, **kwargs)
  File "/home/jyu/project/sssp-project/aiida-core/src/aiida/transports/plugins/ssh.py", line 1413, in exec_command_wait_bytes
    stdout_bytes.append(stdout.read())
  File "/home/jyu/.aiida_venvs/sssp-project/lib/python3.10/site-packages/paramiko/file.py", line 200, in read
    new_data = self._read(self._DEFAULT_BUFSIZE)
  File "/home/jyu/.aiida_venvs/sssp-project/lib/python3.10/site-packages/paramiko/channel.py", line 1361, in _read
    return self.channel.recv(size)
  File "/home/jyu/.aiida_venvs/sssp-project/lib/python3.10/site-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
TimeoutError
```

**Comment by unkcpz** [comment]
Solved with https://github.com/aiidateam/aiida-core/pull/6452, but it then require using with `aiida-core >=2.5.2`. 
It just a false warning, not actually influence real plugin behavior. Closed.
